### ISSUE TITLE
No module named 'lib.utils.cython_bbox'

### ISSUE THREAD

**Issue by Sunny-Li-cpu** [MUSEFood/MUSEFood#2]
Hello, I used your code to do my own image segmentation, but I always see ‘No module named 'lib.utils.cython_bbox'
’ when I run it.I don't know how to solve this mistake. Do you know? I hope you can help me, I will be very grateful

**Comment by umairharon** [comment]
Hi, thanks for the great work, I had the same issue, and after googling it, I feel there is some missing files in the project such as `bbox.c`. Would you please help me out how can I fix this issue. Here is the full stacktrace:

```
/mount/HDD_4TB_1/Umair/Anaconda/envs/muse/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from lib.datasets.factory import get_imdb
  File "/mount/HDD_4TB_1/Umair/projects/FoodEstimation/MUSEFood/Faster-RCNN+Grabcut/lib/datasets/factory.py", line 14, in <module>
    from lib.datasets.pascal_voc import pascal_voc
  File "/mount/HDD_4TB_1/Umair/projects/FoodEstimation/MUSEFood/Faster-RCNN+Grabcut/lib/datasets/pascal_voc.py", line 21, in <module>
    from lib.datasets.imdb import imdb
  File "/mount/HDD_4TB_1/Umair/projects/FoodEstimation/MUSEFood/Faster-RCNN+Grabcut/lib/datasets/imdb.py", line 18, in <module>
    from lib.utils.cython_bbox import bbox_overlaps
ModuleNotFoundError: No module named 'lib.utils.cython_bbox'

```
